# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GetName.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_dialog(object):
    def setupUi(self, dialog):
        dialog.setObjectName("dialog")
        dialog.resize(904, 521)
        self.layoutWidget = QtWidgets.QWidget(dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(470, 20, 421, 481))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.ImagelistWidget = QtWidgets.QListWidget(self.layoutWidget)
        self.ImagelistWidget.setMinimumSize(QtCore.QSize(250, 0))
        self.ImagelistWidget.setObjectName("ImagelistWidget")
        self.verticalLayout_2.addWidget(self.ImagelistWidget)
        self.layoutWidget_2 = QtWidgets.QWidget(dialog)
        self.layoutWidget_2.setGeometry(QtCore.QRect(20, 20, 441, 487))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.IPAddresstextEdit = QtWidgets.QTextEdit(self.layoutWidget_2)
        self.IPAddresstextEdit.setMaximumSize(QtCore.QSize(16777215, 25))
        self.IPAddresstextEdit.setObjectName("IPAddresstextEdit")
        self.horizontalLayout.addWidget(self.IPAddresstextEdit)
        self.ConnectButton = QtWidgets.QPushButton(self.layoutWidget_2)
        self.ConnectButton.setMaximumSize(QtCore.QSize(80, 16777215))
        self.ConnectButton.setObjectName("ConnectButton")
        self.horizontalLayout.addWidget(self.ConnectButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_6 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_6.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_6.addWidget(self.label_6)
        self.TabelSelecetComboBox = QtWidgets.QComboBox(self.layoutWidget_2)
        self.TabelSelecetComboBox.setObjectName("TabelSelecetComboBox")
        self.horizontalLayout_6.addWidget(self.TabelSelecetComboBox)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_7 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_7.setMaximumSize(QtCore.QSize(60, 30))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_4.addWidget(self.label_7)
        self.FeatureComboBox = QtWidgets.QComboBox(self.layoutWidget_2)
        self.FeatureComboBox.setMinimumSize(QtCore.QSize(120, 0))
        self.FeatureComboBox.setObjectName("FeatureComboBox")
        self.verticalLayout_4.addWidget(self.FeatureComboBox)
        self.horizontalLayout_8.addLayout(self.verticalLayout_4)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_8 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_8.setMaximumSize(QtCore.QSize(60, 30))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_5.addWidget(self.label_8)
        self.ItemComboBox = QtWidgets.QComboBox(self.layoutWidget_2)
        self.ItemComboBox.setMinimumSize(QtCore.QSize(150, 0))
        self.ItemComboBox.setObjectName("ItemComboBox")
        self.verticalLayout_5.addWidget(self.ItemComboBox)
        self.horizontalLayout_8.addLayout(self.verticalLayout_5)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.ClearConditionPushButton = QtWidgets.QPushButton(self.layoutWidget_2)
        self.ClearConditionPushButton.setMaximumSize(QtCore.QSize(80, 16777215))
        self.ClearConditionPushButton.setObjectName("ClearConditionPushButton")
        self.verticalLayout_6.addWidget(self.ClearConditionPushButton)
        self.AddConditionPushButton = QtWidgets.QPushButton(self.layoutWidget_2)
        self.AddConditionPushButton.setMaximumSize(QtCore.QSize(80, 16777215))
        self.AddConditionPushButton.setObjectName("AddConditionPushButton")
        self.verticalLayout_6.addWidget(self.AddConditionPushButton)
        self.horizontalLayout_8.addLayout(self.verticalLayout_6)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.BegindateEdit = QtWidgets.QDateTimeEdit(self.layoutWidget_2)
        self.BegindateEdit.setDateTime(QtCore.QDateTime(QtCore.QDate(2018, 1, 1), QtCore.QTime(0, 0, 0)))
        self.BegindateEdit.setDate(QtCore.QDate(2018, 1, 1))
        self.BegindateEdit.setObjectName("BegindateEdit")
        self.horizontalLayout_2.addWidget(self.BegindateEdit)
        self.label = QtWidgets.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.EnddateEdit = QtWidgets.QDateTimeEdit(self.layoutWidget_2)
        self.EnddateEdit.setDate(QtCore.QDate(2019, 4, 12))
        self.EnddateEdit.setObjectName("EnddateEdit")
        self.horizontalLayout_2.addWidget(self.EnddateEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.SQLtextEdit = QtWidgets.QTextEdit(self.layoutWidget_2)
        self.SQLtextEdit.setObjectName("SQLtextEdit")
        self.verticalLayout.addWidget(self.SQLtextEdit)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.QueryPushButton = QtWidgets.QPushButton(self.layoutWidget_2)
        self.QueryPushButton.setObjectName("QueryPushButton")
        self.horizontalLayout_5.addWidget(self.QueryPushButton)
        self.ExportpushButton = QtWidgets.QPushButton(self.layoutWidget_2)
        self.ExportpushButton.setMaximumSize(QtCore.QSize(300, 30))
        self.ExportpushButton.setFlat(False)
        self.ExportpushButton.setObjectName("ExportpushButton")
        self.horizontalLayout_5.addWidget(self.ExportpushButton)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.EnquiryResulttextEdit = QtWidgets.QTextEdit(self.layoutWidget_2)
        self.EnquiryResulttextEdit.setMinimumSize(QtCore.QSize(200, 0))
        self.EnquiryResulttextEdit.setMaximumSize(QtCore.QSize(16777215, 100))
        self.EnquiryResulttextEdit.setObjectName("EnquiryResulttextEdit")
        self.verticalLayout.addWidget(self.EnquiryResulttextEdit)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.ExportprogressBar = QtWidgets.QProgressBar(self.layoutWidget_2)
        self.ExportprogressBar.setMaximumSize(QtCore.QSize(16777215, 30))
        self.ExportprogressBar.setProperty("value", 24)
        self.ExportprogressBar.setObjectName("ExportprogressBar")
        self.verticalLayout_3.addWidget(self.ExportprogressBar)
        self.ExportResulttextEdit = QtWidgets.QTextEdit(self.layoutWidget_2)
        self.ExportResulttextEdit.setMinimumSize(QtCore.QSize(200, 0))
        self.ExportResulttextEdit.setMaximumSize(QtCore.QSize(16777215, 100))
        self.ExportResulttextEdit.setObjectName("ExportResulttextEdit")
        self.verticalLayout_3.addWidget(self.ExportResulttextEdit)
        self.verticalLayout.addLayout(self.verticalLayout_3)

        self.retranslateUi(dialog)
        QtCore.QMetaObject.connectSlotsByName(dialog)

    def retranslateUi(self, dialog):
        _translate = QtCore.QCoreApplication.translate
        dialog.setWindowTitle(_translate("dialog", "图像下载工具"))
        self.label_2.setText(_translate("dialog", "查询结果"))
        self.IPAddresstextEdit.setHtml(_translate("dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#f8f8ff;\"><span style=\" font-family:\'宋体\'; font-size:11.3pt; font-weight:600; color:#000000;\">10.101.170.80:50007</span></p></body></html>"))
        self.ConnectButton.setText(_translate("dialog", "链接"))
        self.label_6.setText(_translate("dialog", "表名选择："))
        self.label_7.setText(_translate("dialog", "Item"))
        self.label_8.setText(_translate("dialog", "Value"))
        self.ClearConditionPushButton.setText(_translate("dialog", "清空Value"))
        self.AddConditionPushButton.setText(_translate("dialog", "添加条件"))
        self.label_4.setText(_translate("dialog", "起始时间："))
        self.label.setText(_translate("dialog", "终止时间："))
        self.QueryPushButton.setText(_translate("dialog", "查询"))
        self.ExportpushButton.setText(_translate("dialog", "导出"))
        self.label_5.setText(_translate("dialog", "查询反馈"))
        self.label_3.setText(_translate("dialog", "导出反馈"))

